# Generated by Django 4.2.6 on 2024-04-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chol_level', models.IntegerField()),
                ('glu_lvl', models.IntegerField()),
                ('hdl_glu', models.IntegerField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('height_cms', models.FloatField()),
                ('weight_kgs', models.FloatField()),
                ('sys_bp', models.IntegerField()),
                ('dia_bp', models.IntegerField()),
                ('waist', models.CharField(max_length=10)),
                ('hip', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
